'''
Author:       James Porter 3140786

Testing gene generation, currently only contains the int generator
'''
## import the os and sys to set the file path for importing main files
import gene_generator

def size_test(genes, size):
    '''Test the size generated by the gene generator'''
    if len(genes) == size:
        return True

    print('content fail')
    return False

def int_content_test(genes, rock_types):
    '''Test the genes are within the set range'''
    for gene in genes:
        if gene < 0:
            print('content fail')
            return False
        if gene > (rock_types - 1):
            return False

    return True

def main():
    '''Run the test'''
    gene_size = 100
    rock_types = 2
    genes = gene_generator.generate_genes_int(gene_size, rock_types)

    result_size = size_test(genes, gene_size)
    result_content = int_content_test(genes, rock_types)

    print('Size test: ' + str(result_size))
    print('Content test: ' + str(result_content))

    if (result_size is True and result_content is True) :
        print('Gene Generator Tests: Passed')
    else:
        print('Gene Generator Tests: Failed')

if __name__ == '__main__':
    main()
